version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: transfer
    ports:
      - "1234:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: ./app
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: python main.py

volumes:
  mysql_data:
