FROM python:3.11-slim

# ติดตั้ง dependencies ที่จำเป็น
# RUN apt-get update && apt-get install -y \
#     build-essential \
#     libssl-dev \
#     && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["gunicorn", "-b", "0.0.0.0:8080", "main:app"]

